### ISSUE TITLE
[Bug]: Icon Color on Black Background

### ISSUE THREAD

**Issue by thenextbutton** [idaho/hassio-trash-card#141]
### Requirements

- [X] I checked the troubleshooting section in the README to verify that I have the latest TrashCard version.
- [X] I did a search to see if there is a similar issue or if a pull request is open.

### Current Behavior

When choosing black for the waste color the icon is not truly visible.

![image](https://github.com/idaho/hassio-trash-card/assets/64163980/9909144d-f759-4b95-85ef-d6422ffd97cd)

### Expected Behavior

Icon color to be different from the waster color (possibly white in this case?)

### Steps To Reproduce

Select Black as the waste color

### Context

YAML state
```yaml

```

### Environment

```markdown
- Browser: Brave, iOS safari, Edge
- HA Version: 20231208.2
- TrashCard: 1.4.0
```

**Comment by idaho** [comment]
Its released in version https://github.com/idaho/hassio-trash-card/releases/tag/1.4.1
