### ISSUE TITLE
[Bug]: Not picking the event from calendar (2 patterns in 1 event, nb of days)

### ISSUE THREAD

**Issue by AlainPeccable** [idaho/hassio-trash-card#145]
### Requirements

- [X] I checked the troubleshooting section in the README to verify that I have the latest TrashCard version.
- [X] I did a search to see if there is a similar issue or if a pull request is open.

### Current Behavior

My agenda contains 1 event with 2 patterns for week 1 and then 2 events with 2 patterns for week 2
week 1:
![image](https://github.com/idaho/hassio-trash-card/assets/132245586/f577b5d9-720e-4d33-8224-9a0c4ad64b02)
week 2:
![image](https://github.com/idaho/hassio-trash-card/assets/132245586/392c45a1-7bdf-4aa8-afe9-31c731cd48de)

The card only shows the first event and the second part of it:
![image](https://github.com/idaho/hassio-trash-card/assets/132245586/d3f6782b-f9e9-4bbd-987f-aba1c668e60a)

changing use summary to true you see that it picked the correct event but didn't split it:
![image](https://github.com/idaho/hassio-trash-card/assets/132245586/0da03bc3-5d76-4036-81f5-bc5f65aa9544)

Events are not configure at day level as mentioned in the doc as this is not working (https://github.com/idaho/hassio-trash-card/issues/143)

### Expected Behavior

I was expecting to see these 2 cards with the same nb of days
![image](https://github.com/idaho/hassio-trash-card/assets/132245586/570e47b4-1de8-4ec2-a38c-c2e647cbbe56)

And the 2 others with another remaining time
![image](https://github.com/idaho/hassio-trash-card/assets/132245586/19fab4b2-b3a7-4c7e-8ead-73c83fc068ee)

### Steps To Reproduce

This is my config:

type: custom:trash-card
drop_todayevents_from: '09:00:00'
next_days: 15
day_style: counter
entity: calendar.me_alaingoossens_be
layout: horizontal
settings:
  organic:
    label: Vert
    icon: mdi:flower
    color: green
    pattern: (vert)
  paper:
    label: Papier
    icon: mdi:newspaper-variant-multiple
    color: yellow
    pattern: (jaune)
  recycle:
    label: PMD
    icon: mdi:recycle-variant
    color: blue
    pattern: (bleu)
  waste:
    label: Poubelle
    icon: mdi:trash-can-outline
    color: black
    pattern: (noir)
  others: {}
fill_container: false
full_size: true
filter_events: true
use_summary: false

### Context

YAML state
```yaml

```

### Environment

```markdown
- Browser: Chrome
- HA Version:2023.12.3
- TrashCard:1.4.1
```

**Comment by idaho** [comment]
Will be available in the next beta release (2.0.0-beta.2)
