### ISSUE TITLE
[Feature]: Icon only mode

### ISSUE THREAD

**Issue by AlainPeccable** [idaho/hassio-trash-card#146]
### Requirements

- [X] I have updated Mushroom to the latest available version
- [X] I did a search to see if there is a similar issue or if a pull request is open.

### Is your feature request related to a problem?

The cards are taking a lot of space while it could be simplified to only an icon and a number.

### Describe the solution you'd like

Have an option to display icon only combine with the counter would give a small card like this but with the trash icons.
![image](https://github.com/idaho/hassio-trash-card/assets/132245586/00fe9db5-1aa3-428a-bee0-c9ea826c6020)

**Comment by idaho** [comment]
@AlainPeccable I've implemented a new chip style in the latest 2.0.0 beta release (2.0.0-beta.3)

**Comment by AlainPeccable** [comment]
Thanks !! Looking great!
![image](https://github.com/idaho/hassio-trash-card/assets/132245586/823bef94-26cc-48a2-9941-9f75248e70d3)

**Comment by idaho** [comment]
I've even added a new 'icon only layout'. #232
