### ISSUE TITLE
[Bug]: Wont show upcoming Garbage Events after update

### ISSUE THREAD

**Issue by esachs4** [idaho/hassio-trash-card#164]
### Requirements

- [X] I checked the troubleshooting section in the README to verify that I have the latest TrashCard version.
- [X] I did a search to see if there is a similar issue or if a pull request is open.

### Current Behavior

After I updated from ver. 1.1.0 to ver.  1.4.3 , it no longer shows my upcoming Garbage Pickups

<img width="277" alt="image" src="https://github.com/idaho/hassio-trash-card/assets/142461937/f490a4a4-c4bc-460a-b56b-6d5aeb166c05">

### Expected Behavior

After I restore from backup to version 1.1.0, it works as expected

<img width="275" alt="image" src="https://github.com/idaho/hassio-trash-card/assets/142461937/0d7d1395-fe5f-4022-a3c7-1518d90b4334">

### Context

type: vertical-stack
cards:
  - type: custom:mushroom-title-card
    title: Upcoming Garbage Pickup
    subtitle: ''
  - drop_todayevents_from: '23:00:00'
    next_days: 1
    day_style: default
    type: custom:trash-card
    settings:
      others:
        icon: ''
        color: orange
      paper:
        label: Cardboard
        color: brown
        pattern: Cardboard
        icon: mdi:newspaper-variant-outline
      waste:
        label: Trash
        color: blue-grey
        icon: mdi:trash-can
        pattern: Trash
      recycle:
        label: Plastic/Cans
        icon: mdi:recycle
        color: indigo
        pattern: Plastic/Cans
      organic:
        label: Yard Waste
        icon: mdi:leaf
        color: amber
        pattern: Yard Waste
    fill_container: false
    use_summary: false
    filter_events: false
    entity: calendar.garbage
  - drop_todayevents_from: '10:00:00'
    next_days: 2
    day_style: default
    type: custom:trash-card
    entity: calendar.yard_waste
    settings:
      others:
        icon: ''
        color: orange
      paper:
        label: Cardboard
        color: brown
        pattern: Cardboard
        icon: mdi:newspaper-variant-outline
      waste:
        pattern: Trash
        label: Trash
        color: blue-grey
        icon: mdi:trash-can
      recycle:
        label: Plastic/Cans
        icon: mdi:recycle
        color: indigo
        pattern: Plastic/Cans
      organic:
        label: Yard Waste
        icon: mdi:leaf
        color: amber
        pattern: Yard Waste
    fill_container: true

### Environment

```markdown
- Browser: Chrome/Edge
- HA Version: 2024.1.2
- TrashCard: 1.4.3
```

**Comment by donverse** [comment]
Check [this bug report](https://github.com/idaho/hassio-trash-card/issues/143) & the solution posted there (confirmed it works for me and at least one other user).

**Comment by esachs4** [comment]
Thank you, I updated to the beta version v2.0.0-beta.0 and it still wont display all day events

**Comment by warmfire540** [comment]
I installed beta, cleared cached and still my full day or not full day appts do not show, was just working yesterday.

**Comment by errolsancaktar** [comment]
i'm seeing the same, not working for full day events even with beta

**Comment by odowd** [comment]
I’ve installed the beta and it only displays the next all day event. It does t display multiple events on the same day or on different days within the look-ahead duration.  This is the same behaviour as the previous version.

**Comment by idaho** [comment]
Please check the latest beta release (Version 2.0.0-beta.4) . If you need help on how to install the latest beta version, have a look at https://hacs.xyz/docs/faq/beta/ .

In the latest beta you are able to activate a debug mode. 

**How you can activate the debug mode**

Edit the trash-card item you have added, open the yaml editor and add `debug: true` to the yaml configuration. 
After that you will see some debug information. At the right top corner you will see a copy icon. Click on this icon to copy the debug information to you clipboard. After that you can remove the added debug line from your yaml configuration.

Please feel free to share your yaml configuration and the debug data so that i'm able to find the reason.

**Comment by idaho** [comment]
The next releases (1.4.6 and 2.0.0-beta.5) will contain the fix
