### ISSUE TITLE
[Bug]: not showing multiple events

### ISSUE THREAD

**Issue by G4Cab** [idaho/hassio-trash-card#181]
### Requirements

- [X] I checked the troubleshooting section in the README to verify that I have the latest TrashCard version.
- [X] I did a search to see if there is a similar issue or if a pull request is open.

### Current Behavior

Only shows one entry

### Expected Behavior

Show all future events

### Context

`drop_todayevents_from: '10:00:00'
next_days: 14
day_style: default
type: custom:trash-card
settings:
  others: {}
  organic:
    label: Biotonne
    icon: mdi:flower-tulip-outline
    color: brown
    pattern: Biotonne
  paper:
    label: Papiertonne
    icon: mdi:newspaper-variant-multiple-outline
    color: blue
    pattern: papiertonne
  recycle:
    label: Gelbe Tonne
    icon: mdi:recycle
    color: yellow
    pattern: Gelbe Tonne
  waste:
    label: Restabfall
    icon: far:trash-can
    color: grey
    pattern: Restabfall 4wö
entity: calendar.muellabfuhr_2
filter_events: false
fill_container: false
`

### Environment

```markdown
Core 2023.12.4
Supervisor 2023.12.1
Operating System 11.2
Frontend 20231208.2
TrashCard 1.4.3
```

### Anything else?

![image](https://github.com/idaho/hassio-trash-card/assets/34376785/72d3872d-f8eb-4275-8fa3-8e4885c2cf46)

**Comment by verboEse** [comment]
Same here. If two types of waste gets collected at the same day only one of them shows up on the dashboard (my notification though reminds me about both of them).

**Comment by idaho** [comment]
Like @Gordontgopher said this is a duplicate
