### ISSUE TITLE
[Feature]: Hide Time

### ISSUE THREAD

**Issue by Marow** [idaho/hassio-trash-card#182]
### Requirements

- [X] I have updated Mushroom to the latest available version
- [X] I did a search to see if there is a similar issue or if a pull request is open.

### Is your feature request related to a problem?

Not at all. But it would be better, without that much infos.

### Describe the solution you'd like

On my card, it shows the time between. That takes a lot of space.

It would be great to disable the time and just show the day

**Comment by Marow** [comment]
Thats how mine looks like. But i cannot remove the time...
![time](https://github.com/idaho/hassio-trash-card/assets/2269012/6e65c340-77f7-4ea8-8231-15da65a7cb9f)

**Comment by idaho** [comment]
@Marow will be included in the next v2 beta release.
