### ISSUE TITLE
Guidance on how to get this to work

### ISSUE THREAD

**Issue by aquariuz23** [idaho/hassio-trash-card#195]
Hello all,

I’ve been wrecking my brain trying to figure out how to get Trashcard to work when added to my dashboard. I’ve tried following the instructions to the best of my understanding, but it just doesn’t seem to wanna show up. I'm not sure what else I need to do so I'm forced to ask for help here.

I’ve created a local calendar, as required, with two events in it, Trash and Recycling.

![image](https://github.com/idaho/hassio-trash-card/assets/48851656/3545d791-64a5-4ef7-864e-f4c57863d7f0)

I also already have Mushroom installed. Within my dashboard configuration, I’ve configured Trashcard in this manner.

![image](https://github.com/idaho/hassio-trash-card/assets/48851656/b2524cf1-67c5-4489-8136-6a2d275fdcd0)

As instructed, the detection patterns are named exactly as the events in the calendar, but yet, no card shows up in the preview.

I’m not sure what I’m doing wrong. I tried looking around for more guidance but I guess most people just manage to get working without any issues, since I don't see anyone asking about how to set this up.

Please help. I really want to add this to my dashboard as it would be very useful for me. Thank you in advance.

**Comment by idaho** [comment]
@aquariuz23 have you tried the beta release? (2.0.0-beta.2) There are some new features, editor layout etc. https://github.com/idaho/hassio-trash-card/issues/78#issuecomment-1877674062 Currently i'm only working on the version 2 release and want fix the version 1 any more only some dependency updates

**Comment by aquariuz23** [comment]
> @aquariuz23 have you tried the beta release? (2.0.0-beta.2) There are some new features, editor layout etc. [#78 (comment)](https://github.com/idaho/hassio-trash-card/issues/78#issuecomment-1877674062) Currently i'm only working on the version 2 release and want fix the version 1 any more only some dependency updates

Idaho, thank you very much for your reply. I will give that a try and let you know how it goes. I hope it will work :)

**Comment by idaho** [comment]
@italocp04, @aquariuz23  please update to the latest release (2.0.0-beta.4) in there is a debug mode implemented.

**How you can activate the debug mode**

Edit the trash-card item you have added, open the yaml editor and add debug: true to the yaml configuration.
After that you will see some debug information. At the right top corner you will see a copy icon. Click on this icon to copy the debug information to you clipboard. After that you can remove the added debug line from your yaml configuration.

Please feel free to share your yaml configuration and the debug data so that i'm able to find the reason.

**Comment by aquariuz23** [comment]
Hi @idaho, 

My apologies but I can't seem to find a way to update to the latest release, so I just removed my existing trashcard from HACS and added the trashcard.js for 2.0.0-beta 4 file into www folder, and followed the remaining manual install guide. Please let me know if I did this incorrectly.

I also decided to add the card to a different dashboard to eliminate the potential of a conflict with another card. 

Here is the debug log that appeared on the right side preview display with pink background. There was no "copy" icon, so I just highlighted the text and copy it. 

`DEBUG LOG
timezone:
"-5:00"
calendar data:
[{"start":{"date":"2024-02-21"},"end":{"date":"2024-02-22"},"summary":"Recycling","description":"Recycling","location":null,"uid":"4d85803a-cada-11ee-9e6d-52540047e0d7","recurrence_id":"20240221","rrule":"FREQ=WEEKLY;INTERVAL=2;BYDAY=WE"},{"start":{"date":"2024-02-22"},"end":{"date":"2024-02-23"},"summary":"Trash","description":"Trash","location":null,"uid":"3596085a-cada-11ee-9e6d-52540047e0d7","recurrence_id":"20240222","rrule":"FREQ=WEEKLY;BYDAY=TH,MO"}]
normaliseEvents:
[{"date":{"start":null,"end":null},"isWholeDayEvent":true,"content":{"summary":"Recycling","description":"Recycling","location":null,"uid":"4d85803a-cada-11ee-9e6d-52540047e0d7","recurrence_id":"20240221","rrule":"FREQ=WEEKLY;INTERVAL=2;BYDAY=WE"}},{"date":{"start":null,"end":null},"isWholeDayEvent":true,"content":{"summary":"Trash","description":"Trash","location":null,"uid":"3596085a-cada-11ee-9e6d-52540047e0d7","recurrence_id":"20240222","rrule":"FREQ=WEEKLY;BYDAY=TH,MO"}}]
dropAfter:
true
now:
"2024-02-21T16:04:01.906Z"
activeElements:
[]
eventsToItems:
[]`

And here is the yaml of the configuration - 

`event_grouping: true
drop_todayevents_from: '10:00:00'
next_days: 2
settings:
  organic:
    icon: mdi:flower
  paper:
    icon: mdi:newspaper
  recycle:
    icon: mdi:recycle-variant
    color: orange
    label: Recycling Day
    pattern: Recycling
  waste:
    icon: mdi:trash-can-outline
    pattern: Trash
    label: Trash Day
  others:
    icon: mdi:dump-truck
items_per_row: 1
refresh_rate: 60
type: custom:trash-card
entity: calendar.trash_and_recycling
filter_events: false
full_size: false
hide_time_range: false`

I also included the screenshot of how it looks as I configure the card. The preview now just displays a small black box

![image](https://github.com/idaho/hassio-trash-card/assets/48851656/4c431da2-4089-4001-8a8a-aaeabed0e13c)

Please let me know any other way I can test this. Just as a note, I'm still using the same calendar as my original post above.

**Comment by idaho** [comment]
@aquariuz23 Thank you for your information. This helps a lot. The next releases (1.4.6 and 2.0.0-beta.5) will contain the fix

**Comment by aquariuz23** [comment]
> @aquariuz23 Thank you for your information. This helps a lot. The next releases (1.4.6 and 2.0.0-beta.5) will contain the fix

@idaho, my pleasure, glad to be of help! :) Looking forward to the next update. 👍

**Comment by italocp04** [comment]
The 2.0.0-beta.5 release worked for me.
Thank you for the assistance.

**Comment by aquariuz23** [comment]
Confirming as well that it now works with 2.0.0 - beta 5! Thank you very much for working on the fix.

![image](https://github.com/idaho/hassio-trash-card/assets/48851656/009a4a06-7845-4f13-9e7c-11708f58e616)
