### ISSUE TITLE
[Feature]: Add second line to "chip"layout

### ISSUE THREAD

**Issue by mistergyle** [idaho/hassio-trash-card#236]
### Requirements

- [X] I have updated Mushroom to the latest available version
- [X] I did a search to see if there is a similar issue or if a pull request is open.

### Is your feature request related to a problem?

additional value for chip-layout

### Describe the solution you'd like

Currently the Chip-layout has only one label in a single line (eg. "Morgen" or "in 2 Tagen")
I would like to use the chip-layout with the **additional label of the trash-type** (eg. "Biomüll" or "Gelber Sack")

result would look like this:
(icon) **Biomüll**
_______in 2 Tagen_

**Comment by idaho** [comment]
Possible solution could look like 
![Chip-with-label](https://github.com/idaho/hassio-trash-card/assets/664101/b03329fe-892a-4d98-b277-1120923a7035)
What do you think about that?

**Comment by mistergyle** [comment]
Love it 😍

**Comment by mistergyle** [comment]
Thanks
