### ISSUE TITLE
[Feature]: Change the color of the entity, the day before the event

### ISSUE THREAD

**Issue by Djivouille** [idaho/hassio-trash-card#250]
### Requirements

- [X] I have updated Mushroom to the latest available version
- [X] I did a search to see if there is a similar issue or if a pull request is open.

### Is your feature request related to a problem?

Currently my card is like this:
![image](https://github.com/idaho/hassio-trash-card/assets/48792341/7d45a59b-3bda-4bad-8506-80779650c31d)

### Describe the solution you'd like

 be able to change the background color of the entity the day before the event to indicate that the garbage can is to be taken out.
 
Something like this : 

![image](https://github.com/idaho/hassio-trash-card/assets/48792341/2dd569e5-d646-4ef8-9231-09e451f5ea52)

and i confirm that a click on the entity to indicate that the garbage can has been taken out and change the background color .... would be great.

ps : 
a short date, type dd/mm/YYYY ( to be displayed on one line only) could be nice

Thanks for the work already done!
:)

### Describe alternatives you've considered

--

### Additional context

--

**Comment by idaho** [comment]
@Djivouille i think more extra styling function will blow up the card settings, but i've already some change in the pipeline where a class is set on the ha-card with a class to identify if its today, tomorrow or another day. After that you can use card mod and add something like

```yaml
card_mod:
  style: |
    ha-card.tomorrow, ha-card.today  {
      --card-primary-color: var(--primary-background-color) !important;
      --card-secondary-color: var(--primary-background-color) !important;
      --icon-primary-color: var(--primary-background-color) !important;
      background-color:var(--trash-card-icon-color);
    }
```

to the card configuration. Than it would look like in your examples.

For the date, you can use the new `custom date` option and set it

```yaml
day_style: custom
day_style_format: dd/MM/YYYY
```

**Comment by Djivouille** [comment]
it's works well for the date format : 
![image](https://github.com/idaho/hassio-trash-card/assets/48792341/0fd309f8-7ed9-41db-8b3e-b961a59f71e8)

about the changing color, i think you right,
i had the style : 

`event_grouping: true
drop_todayevents_from: '10:00:00'
next_days: 8
pattern:
  - icon: mdi:leaf
    color: green
    type: organic
    pattern: Déchets verts
    label: Déchets verts
  - icon: mdi:newspaper
    color: blue
    type: paper
  - icon: mdi:recycle
    color: yellow
    type: recycle
    pattern: Poubelle Jaune
    label: Poubelle Jaune
  - icon: mdi:trash-can-outline
    color: red
    type: waste
    pattern: Poubelle Grenat
    label: Poubelle Grenat
  - icon: mdi:dump-truck
    color: purple
    type: others
day_style: custom
day_style_format: dd MM yyyy
color_mode: icon
items_per_row: 3
refresh_rate: 60
with_label: true
type: custom:trash-card
entities:
  - calendar.poubelle
filter_events: false
hide_time_range: true
use_summary: false
full_size: false
layout: vertical
card_mod:
  style: |
    ha-card.tomorrow, ha-card.today  {
      --card-primary-color: var(--primary-background-color) !important;
      --card-secondary-color: var(--primary-background-color) !important;
      --icon-primary-color: var(--primary-background-color) !important;
      background-color:var(--trash-card-icon-color);
    }
`
but it will work after your next release ? right ?

**Comment by idaho** [comment]
@Djivouille it's now available in the last release

**Comment by idaho** [comment]
Try setting the color_mode to icon

```yaml
color_mode: icon
```

I've modified it with card-mod to look like this

<img width="390" alt="Screenshot 2024-04-03 at 07 22 42" src="https://github.com/idaho/hassio-trash-card/assets/664101/035a1f10-972d-41a5-92db-0d44ce306550">
