### ISSUE TITLE
customize date

### ISSUE THREAD

**Issue by purewhitedesign** [idaho/hassio-trash-card#258]
### Requirements

- [X] I have updated Mushroom to the latest available version
- [X] I did a search to see if there is a similar issue or if a pull request is open.

### Is your feature request related to a problem?

no

### Describe the solution you'd like

I can only choose the date of the event or the days counted. The date is formatted to "DAY, DDMMMYYYY", but I want it in a shorter form, i.e.: DD/MM/YYYY or DD/MM.
Thanks!

**Comment by idaho** [comment]
@purewhitedesign you can now choose between "counter" the predefined "default" date format and the new "custom" format option. After that there will a new text field where you can add a date format like 'yyyy/MM/dd' or 'dd/MM' 

Available 
- day: `d`, `dd`
- month: `M`, `MM`
- year: `y`, `yy`, `yyy`, `yyyy`

**Comment by purewhitedesign** [comment]
This is awesome! Thank you so much! You will get a coffee for sure 💯

**Comment by Djivouille** [comment]
It's rock !
![image](https://github.com/idaho/hassio-trash-card/assets/48792341/a36b8ae8-ef80-45c8-ac55-517f86adb18c)

Thank you !
👍

**Comment by purewhitedesign** [comment]
Yes, now it fit's perfectly into my phone display!
![IMG_1453](https://github.com/idaho/hassio-trash-card/assets/160245115/2a6c9333-d28a-4026-8bfa-a9ab6050f611)

Now, we could try to get another type of format, like "shortday, dd.MM." 😄 
Mi, 13.03. for example.
