### ISSUE TITLE
Weekday in "Custom Date"

### ISSUE THREAD

**Issue by BrunoMilan** [idaho/hassio-trash-card#269]
### Requirements

- [X] I have updated Mushroom to the latest available version
- [X] I did a search to see if there is a similar issue or if a pull request is open.

### Is your feature request related to a problem?

I would like to see only the weekday instad of dd.mm.yyy, because is too long

### Describe the solution you'd like

I think that the custom date format have to accept also ddd for the weekday

**Comment by choenig** [comment]
Please implement this.

I've never seen someone restrict a date formatter in such a way. Please allow all possible date formatter options that are supported by DateTime :)

**Comment by idaho** [comment]
Solved in #405
