### ISSUE TITLE
[Feature]: Exact pattern matching

### ISSUE THREAD

**Issue by stieler-it** [idaho/hassio-trash-card#361]
### Requirements

- [X] I have updated Mushroom to the latest available version
- [X] I did a search to see if there is a similar issue or if a pull request is open.

### Is your feature request related to a problem?

Our city offers different frequencies of pickup of the same trash type. The workers can identify it by the color of the lid of the trashcans and this also leads to similar names in the ICS, e.g. "Paper" and "Paper (yellow lid)". If I now specify a pattern of "Paper" it matches both, although I only want to match the first one.

### Describe the solution you'd like

Add an option "exact match" to define a pattern that needs to, well, match exactly, not just a part of the entry

### Describe alternatives you've considered

I also thought about integrating regular expressions. So one could write `^Paper$`. Maybe there could be some kind of auto-detection if the pattern is a string or a reg.exp.

**Comment by Arcane1980** [comment]
I don't fully understand your integration issue.

Are you pulling on calendar entries that you have control over or are you pulling from a calendar run by your garbage collection or council entity?

If it is your own calendar, then perhaps putting unique names yourself rather than relying on the standard format. If it is an external calendar you cannot edit, how often does the actual routine change? If it is a set routine for YOUR bin collection, maybe ignoring the provided calendar and creating your own entries would be the easiest and simplest way to achieve this.

Just spit balling solutions whilst a feature addition is still a ways off.

**Comment by stieler-it** [comment]
Thanks for asking questions for clarifications. We are using a provided calendar. Our city offers two service levels for garbage, they show up in the calendar as "Restmüll" und "Restmüll (grüner Deckel)" which translates to "Garbage" and "Garbage (green lid)".
Relevant for us is only "Garbage" but the current filter also shows "Garbage (green lid)".
The routine does not actually change, it is like weekly versus 4 weekly so every few weeks we see a wrong entry.

**Comment by stieler-it** [comment]
Thank you, it's not frustrating just a small inconvenience happening every few weeks.
To your solution idea: Combining different items seems a too complicated approach and doesn't fully match the real-life problem. I think making it possible to chosse an exact match instead of a regexp match for entries would be closer.

**Comment by stieler-it** [comment]
Hello @idaho, thank you for implementing the exact pattern matching. It works but unfortunately doesn't solve my problem. When I activate it for "Restmüll" the events with suffix "Restmüll (grüner Deckel)" are still shown, now just by the "other" pattern. `filter_events` is true. I also tried to remove the other pattern in the YAML but then the events are still shown, just without color and icon.
Can we define a pattern to be excluded or have a setting that only defined patterns are shown (without a catch all other pattern), or should the latter happen with the filter_events option?

**Comment by stieler-it** [comment]
@idaho Just stared at your code for an hour not finding any issue with it, now I noticed you have already fixed it. Thank you so much for the quick response!
