### ISSUE TITLE
[Bug]: Difficult to see Icons - colour has changed

### ISSUE THREAD

**Issue by godfreym29** [idaho/hassio-trash-card#408]
### Requirements

- [X] I checked the troubleshooting section in the README to verify that I have the latest TrashCard version.
- [X] I did a search to see if there is a similar issue or if a pull request is open.

### Current Behavior

The icons in the Standard card have changed to a light grey colour and are difficult to see
![after](https://github.com/user-attachments/assets/1c69596d-a822-421d-b3cd-9d535dd0c976)

### Expected Behavior

Previously they were more of a contrast and stood out
![before](https://github.com/user-attachments/assets/5b10494b-6f87-4a60-a006-7f12f99809ee)

### Steps To Reproduce

Add a new card and configure it with your council and 14 days future
Set the colour for each service to match your bin

### Context

YAML state
```yaml

```

### Environment

```markdown
- Browser: Chrome Version 129.0.6668.60
- HA Version: 2024.9.3
- TrashCard: 2.3.2
```

**Comment by samuelecarpene** [comment]
I have the same problem.
I checked the css and icons (ha-tile-icon) are taking color from var --tile-color 
![image](https://github.com/user-attachments/assets/55b67639-8f27-4279-856b-d770c96c8deb)

**Comment by idaho** [comment]
What do you think of this?

<img width="1495" alt="dark" src="https://github.com/user-attachments/assets/1db6ec39-3e65-4780-806b-9d16608f4690">
<img width="1512" alt="light" src="https://github.com/user-attachments/assets/079e364e-b230-407d-92eb-c22f41dbe144">

**Comment by godfreym29** [comment]
> What do you think of this?
> 
That looks much better

**Comment by Stoony1** [comment]
Same Problems..

https://github.com/idaho/hassio-trash-card/pull/407#issuecomment-2384036866
