### ISSUE TITLE
Changing language to another does not work. 

### ISSUE THREAD

**Issue by kaldurhan** [idaho/hassio-trash-card#441]
### Requirements

- [X] I checked the troubleshooting section in the README to verify that I have the latest TrashCard version.
- [X] I did a search to see if there is a similar issue or if a pull request is open.

### Current Behavior

I change language in the current users General settings to another language. In this case Swedish. When i do my other cards switch language as they should however the trash-cards does not. I've tried to change the local language settings also in the server but this did not help either.
When doing debug i can see that the timezone is always +2:00 even though my timezone is +1:00 (UTC +1). So i can see that there is something wrong but i cannot understand where the issue is.  

### Expected Behavior

Change language in the trash card

### Steps To Reproduce

Change language to another language in the user.

### Environment

```markdown
- Browser: Chrome Version 129.0.6668.101
Core
2024.10.2
Supervisor
2024.10.0
Operating System
13.1
Frontend
20241002.3
- TrashCard:2.4.1

- Iphone app: 2024.9.4
```

### Debug data

```json
For some reason i cannot copy the debug log in either chrome or edge. i have attached screenshots of the debug

YAML:
  - type: custom:trash-card

    entities:
      - calendar.trashcollection
    layout: vertical
    fill_container: false
    event_grouping: false
    full_size: true
    drop_todayevents_from: '23:00:00'
    next_days: 7
    day_style: counter
    card_style: chip
    color_mode: icon
    items_per_row: 3
    refresh_rate: 60
    with_label: true
    filter_events: true
    use_summary: true
    hide_time_range: false
    language: se
    pattern:
      - label: Kärl 1
        icon: mdi:recycle-variant
        pattern: Kärl 1
        color: light-green
        type: recycle
      - label: Kärl 2
        icon: mdi:recycle-variant
        pattern: Kärl 2
        color: light-green
        type: waste
      - label: Trädgårdsavfall
        icon: mdi:flower
        pattern: Trädgårdsavfall
        color: amber
        type: organic
```

### Anything else?

![ActiveElements](https://github.com/user-attachments/assets/bff7dfd5-a6d5-4410-8aa9-3ec3cebf5809)
![calender data](https://github.com/user-attachments/assets/9c0eed61-f17c-4166-9aa9-4b29c74c72d0)
![dropafter](https://github.com/user-attachments/assets/009e78c4-2474-4f60-be2b-3541e5faff30)
![EventsToitems1-2](https://github.com/user-attachments/assets/d7c5a93a-521f-4048-ab91-173741c0cf96)
![EventsToitems2-2](https://github.com/user-attachments/assets/98cc8492-a7e9-4d74-9e30-768fc86748f4)
![normaliseevents](https://github.com/user-attachments/assets/c295b299-ebfc-44c2-908b-d1d345bfff3a)
![Now](https://github.com/user-attachments/assets/9bc20002-d087-4a6f-bb27-fb14e17b4927)
![timezone](https://github.com/user-attachments/assets/c4b1c4a5-e0a0-4897-bb78-ce500f727dd3)

**Comment by idaho** [comment]
@kaldurhan the short code for swedish was wrong, so the translation into swedish wasn't available. 

I'm not sure about your time zone. If you are in sweden your timezone should be UTC+2.

Excerpt from google 

In Sweden, the standard time is Central European Time (CET; UTC+01:00; Swedish: centraleuropeisk tid). Daylight saving time is observed from the last Sunday in March (02:00 CET) to the last Sunday in October (03:00 CEST).

Or see here https://www.timeanddate.com/time/zone/sweden, https://www.campervansweden.com/blog/travel-information/what-time-is-it-in-sweden

The time zones here always refer to UTC and not GMT

Translated with DeepL.com (free version)

**Comment by tbowmo** [comment]
@idaho the changes doesn't make sense, the two letter shortname for Sweden is se, according to https://www.iban.com/country-codes, but now you've changed the language file to sv? Which is El Salvador, according to the link..
