### ISSUE TITLE
[Translation]: Czech 

### ISSUE THREAD

**Issue by MattXcz** [idaho/hassio-trash-card#462]
### Type of request

Updates / fixes to a existing language

### For which language you want to make a request

cs

### Content of the translations

```
            "today": "dnes",
            "tomorrow": "zítra",
            "day": "<DAY>",
            "today_from_till": "Dnes\nod <START> do <END>",
            "tomorrow_from_till": "Zítra\nmezi <START> and <END>",
            "day_from_till": "<DAYS>\nmezi <START> a <END>",
            "daysleft": "za <DAY> den",
            "daysleft_more": "za <DAYS> dní",
            "daysleft_from_till": "za <DAYS> den\nmezi <START> a <END>",
            "daysleft_more_from_till": "za <DAYS> dní\nmezi <START> a <END>"
```

fixed `<DAY> to <DAYS>`

**Comment by MattXcz** [comment]
![image](https://github.com/user-attachments/assets/79bb85ec-d1d4-4e14-9183-0cd52ce86125)

**Comment by MattXcz** [comment]
Also mentioned in #443

**Comment by sympatickejsam** [comment]
`            "today": "dnes",
            "tomorrow": "zítra",
            "day": "dny/í",
            "today_from_till": "dnes od <START> do <END>",
            "tomorrow_from_till": "zítra od <START> do <END>",
            "day_from_till": "za <DAYS> dny/í od <START> do <END>",
            "daysleft": "za <DAY> den",
            "daysleft_more": "za <DAYS> dny/í",
            "daysleft_from_till": "za <DAYS> den od <START> do <END>",
            "daysleft_more_from_till": "za <DAYS> dny/í od <START> do <END>"`
