### ISSUE TITLE
Can't get multple pickups a day to work.

### ISSUE THREAD

**Issue by SigurdVie** [idaho/hassio-trash-card#78]
Hey! First off, thanks for the card! I just have some problems with it, might be me just misunderstanding it ofc.

I use https://github.com/mampfes/hacs_waste_collection_schedule to create a schedule of when my garbage is picked up, and it creates separate whole day events for those pickups. So for example; on Monday I have a pickup for waste and organics. But instead of displaying both, the card only displays the waste. Any idea why?

I have double check to see what the actual names the waste collection scheduler is assigning them.

(Matavfall is essentially organics and resavfall is essentially waste)
![image](https://github.com/idaho/hassio-trash-card/assets/49611200/14f3bc93-6936-4c99-ba18-c20f15bbb874)

![image](https://github.com/idaho/hassio-trash-card/assets/49611200/4eff52b1-4992-48f1-b830-a57a4c096697)

**Comment by jankete** [comment]
I can also confirm this.

**Comment by Klorins** [comment]
For me it only shows up if the event is the same day or the next day.. not the next event in calendar.

**Comment by Slippery-Silvia** [comment]
I feel the options in this card mislead me to believe multiple bins could be configured from the single card.
maybe group the options with dropdowns or something?

this is an example of my custom mushroom card. that i am still using until being able to use trash card with multiple days.

Would we be able to choose a sensor instead of a calendar date?

I am sure it could be better done, but it works well for me.

 - type: custom:mushroom-template-card
        primary: ''
        secondary: |-
          {{ states('sensor.general_waste') }} 
          {{ states('sensor.recyclable_waste') }} 
        icon: >-
          {% if is_state('sensor.recyclable_waste', 'Recyclable waste in 6
          days') %}
            mdi:recycle
          {% elif is_state('sensor.recyclable_waste', 'Recyclable waste in 5
          days') %}
            mdi:recycle
          {% elif is_state('sensor.recyclable_waste', 'Recyclable waste in 4
          days') %}
            mdi:recycle
          {% elif is_state('sensor.recyclable_waste', 'Recyclable waste in 3
          days') %}
            mdi:recycle
          {% elif is_state('sensor.recyclable_waste', 'Recyclable waste in 2
          days') %}
            mdi:recycle
          {% elif is_state('sensor.recyclable_waste', 'Recyclable waste in 1
          days') %}
            mdi:recycle
          {% elif is_state('sensor.recyclable_waste', 'Recyclable waste in 0
          days') %}
            mdi:recycle
          {% else %}
            mdi:trash-can-outline
          {% endif %}
        entity: sensor.recyclable_waste
        multiline_secondary: true
        icon_color: >-
          {% if is_state('sensor.recyclable_waste', 'Recyclable waste in 6
          days') %}
            yellow
          {% elif is_state('sensor.recyclable_waste', 'Recyclable waste in 5
          days') %}
            yellow
          {% elif is_state('sensor.recyclable_waste', 'Recyclable waste in 4
          days') %}
            yellow
          {% elif is_state('sensor.recyclable_waste', 'Recyclable waste in 3
          days') %}
            yellow
          {% elif is_state('sensor.recyclable_waste', 'Recyclable waste in 2
          days') %}
            yellow
          {% elif is_state('sensor.recyclable_waste', 'Recyclable waste in 1
          days') %}
            yellow
          {% elif is_state('sensor.recyclable_waste', 'Recyclable waste in 0
          days') %}
            yellow
          {% else %}
            green
          {% endif %}
        tap_action:
          action: more-info
        fill_container: true
        layout: horizontal

<img width="373" alt="image" src="https://github.com/idaho/hassio-trash-card/assets/51182742/5a5cfcaa-ad46-4d16-a685-3496e29b4634">

**Comment by SigurdVie** [comment]
> My thoughts about your questions:
> 
> I think it would be good if we could configure how far it looks into future. Some may prefer 2 days and others would be happy with 2 weeks. Or it could the display the next date for each label without giving a timespan.
> 
> And when there are multiple pickups the same day, all of them should be displayed.

Yeah, I really agree with you here @jankete, having it be configurable by the users would be great. And having it display multiple pickups the same day would also be great! As that is what I originally thought the card did.

**Comment by markjsmith** [comment]
I really like how it displays and have tested it to show birthdays, and it works! But just shows the label which I set to Birthday. It would be great if you could set the label or have an option to use the event label instead? This would work well for multiple events too to differentiate them.

**Comment by idaho** [comment]
> My thoughts about your questions:
> 
> I think it would be good if we could configure how far it looks into future. Some may prefer 2 days and others would be happy with 2 weeks. Or it could the display the next date for each label without giving a timespan.
> 
> And when there are multiple pickups the same day, all of them should be displayed.

I've created a new PR to implement at first a config setting for the next days we want to inspect. #106 #93

**Comment by Lethal83** [comment]
> Hey, currently it supports only the first event which comes up and is a whole day event. I'm currently working on it to show multiple whole day events and even non whole day events. Even it will only have a look for the next 2 days.
> 
> So possible you can give me some answers about some wishes you have beside support of multiple events.
> 
> * How far it should look into the future? ( currently 2 days, which is hard coded )
> * What is, if you have today some pickup and in two days the next one. Should both be displayed or should there be a time when the current event should disappear and the next should be shown?

Thanks for creating this. I’ll chime in with my 2 cents. 
I would like to see it as a configurable time frame to see how far ahead to look. Me personally would like to see what tomorrow is, then what today is, then what the next weeks pickup is. My situation is general waste or rubbish is weekly, then we only have recycling, and green waste (aka organic) which alternate each fortnight. So I would like it to show Rubbish and Recycling tomorrow, Or Rubbish and Greenwaste today. Then Rubbish and Recycling in 5 days. 
Keep up the awesome work.

**Comment by Framstag** [comment]
Hi, also have the problem, that it only shows the first event of two event at the same day. Regarding your questions:

IMHO the ground question is, what are the visual semantics of the component? Is it a timeline or is it a notification (like on a mobile) for an event or...?

I would like to behave it like a timeline with a configurable amount of days to look up in the future (where 2 days is a good default value). So if there are two "fetches" tomorrow and one the day after that, it should show all of them - but possibly visual distinguished (lighter color for later events or some gap?).

It is OK, if it will only show the next fetching slot, but in this case with all events for that day (of course).

It should still be effectively invisible if there is no event at all...

**Comment by idaho** [comment]
Hey,
so I've some ideas how to show more than only the next event.

This needs a bit more preparations.

First i will redesign the editor. At the moment it is really full of features and getting more. 
My idea is to have a tab for the appereance and one for the pattern  settings. In those we can than add more custom patterns and not only the predefined ones.

Possible with some more pattern settings for the label which is displayed and using regular expression or a normal string matching (simple and expert mode)

An option to toggle the date info line. So that that it will show the day or how many days are left till this event.

An option at which time a whole day event should disappear.

A feature which filters non matching events (There is a PR for it #113).

And two different views. 
- A simple view which shows the current events. Not only one for the current / next day
- A timeline / flow view. In here it will show the current active events. The next important, like what will be picked up tomorrow and a small preview for the next X days (which will only show colors, icons, and a days till info)

**Comment by idaho** [comment]
I'm currently working on a new release. I've create a beta release which contains 

- New editor layout
- Showing multiple events

https://github.com/idaho/hassio-trash-card/releases/tag/2.0.0-beta.0

How to get the beta https://hacs.xyz/docs/faq/beta/

Next steps:

- Beautify UI

**Comment by dMopp** [comment]
> I'm currently working on a new release. I've create a beta release which contains
> 
>     * New editor layout
> 
>     * Showing multiple events
> 
> 
> https://github.com/idaho/hassio-trash-card/releases/tag/2.0.0-beta.0
> 
> How to get the beta https://hacs.xyz/docs/faq/beta/
> 
> Next steps:
> 
>     * Beautify UI

NICE addon, even more nice beta version. Many thanks (WAF increased  a lot again  :D)

**Comment by verboEse** [comment]
I do have the 2.0.0-beta.0 installed, but of the two pickups next Tuesday only one is shown in the dashboard. Beside that, I *love* the module. Thanks for your great work!

**Comment by verboEse** [comment]
Correction: Must be something with Browser caching. On a private Browser window it works!

**Comment by waspxx** [comment]
could you please share yaml card?

**Comment by Klorins** [comment]
> could you please share yaml card?

Sure:
`  - drop_todayevents_from: '15:00:00'
    next_days: 3
    settings:
      organic:
        icon: mdi:flower
        label: Organisk
        color: purple
      paper:
        icon: mdi:newspaper
        label: Papir
        pattern: Papir
        color: blue
      recycle:
        icon: mdi:recycle-variant
        color: teal
        pattern: Plast
        label: Plastic and paper
      waste:
        icon: mdi:trash-can-outline
        label: Trash and organic
        color: cyan
        pattern: Rest-
      others:
        icon: mdi:dump-truck
    type: custom:trash-card
    entity: calendar.granum
    filter_events: true
    fill_container: false
    full_size: false
    use_summary: false`

**Comment by sgtsilver** [comment]
Having Beta 2.0.0-beta2 installed - Not seeing more than one event.

`drop_todayevents_from: '15:00:00'
next_days: 31
settings:
  organic:
    icon: mdi:flower
    label: Biotonne
    color: green
    pattern: Biotonne
  paper:
    icon: mdi:newspaper
    label: Papiermüll
    color: blue
    pattern: Papiertonne
  recycle:
    icon: mdi:recycle-variant
    color: yellow
    pattern: Gelbe Wertstofft*
    label: Gelbe Tonne
  waste:
    icon: mdi:trash-can-outline
    label: Restmüll
    color: black
    pattern: Restmülltonne
  others:
    icon: mdi:dump-truck
type: custom:trash-card
entity: calendar.srh_abfuhren
filter_events: true
fill_container: false
full_size: false
use_summary: false`

**Comment by idaho** [comment]
Hello some small updates to the next version, already implemented

### Features 🎉
implement alternative chip style by @idaho in https://github.com/idaho/hassio-trash-card/pull/211
Implement color mode option by @idaho in https://github.com/idaho/hassio-trash-card/pull/213
Option to define refresh rate by @idaho in https://github.com/idaho/hassio-trash-card/pull/214
option to disable event grouping by @idaho in https://github.com/idaho/hassio-trash-card/pull/200
Option to hide time by @idaho in https://github.com/idaho/hassio-trash-card/pull/192

### Bug Fixes 🐛
calculation of days till event by @idaho in https://github.com/idaho/hassio-trash-card/pull/190
get multiple items from single event by pattern by @idaho in https://github.com/idaho/hassio-trash-card/pull/201
Fix match always lower case by @idaho in https://github.com/idaho/hassio-trash-card/pull/216

## Next Feature

Implementing feature where it is possible to add as much custom pattern as you like next to the five predefined

BTW - see my Issue #209 ;)

**Comment by idaho** [comment]
finally version 2.0.0 is release, i think most of the features and fixes are now included, i will close the issue
