### ISSUE TITLE
Card Scale

### ISSUE THREAD

**Issue by Slippery-Silvia** [idaho/hassio-trash-card#83]
Having troubles getting the card to scale correctly.
Image below to show how it looks
<img width="671" alt="image" src="https://github.com/idaho/hassio-trash-card/assets/51182742/af208777-0108-4d99-92ed-937ef9cf5011">
<img width="592" alt="image" src="https://github.com/idaho/hassio-trash-card/assets/51182742/01db323e-8bab-473b-b198-15966c21a83e">
<img width="752" alt="image" src="https://github.com/idaho/hassio-trash-card/assets/51182742/61e9b610-0070-49d9-a2ea-c5be98687d47">

**Comment by Zunhammer** [comment]
Same problem for me

**Comment by Latschenharry** [comment]
Same here

**Comment by Klorins** [comment]
Yep, same here.

**Comment by Maxlueckg** [comment]
Same here

**Comment by idaho** [comment]
Should be fixed within the next release #88
