### ISSUE TITLE
please help set this card up (only got "invalid date")

### ISSUE THREAD

**Issue by prankousky** [idaho/hassio-trash-card#92]
Hi everybody,

I subscribe to my local trash pickup services `*.ics`  , so I doubt this has to do with me messing up the ical format...

I installed the card, reloaded Home Assistant, then added the calendar entity to the card. 

As you can see here, it will actually detect *something* (in this case, **only** organic, even though paper will be picked up tomorrow as well), but it has some issue with the date.

![grafik](https://github.com/idaho/hassio-trash-card/assets/11297070/af1ee499-b622-45e3-b87a-80db06dbb4fa)

The calendar is displayed in the Home Assistant calendar without issues, which lets me assume that the date is formatted correctly..?

![grafik](https://github.com/idaho/hassio-trash-card/assets/11297070/bd009180-37c5-407f-8968-e37f088a7210)

I tried to minimize the card as much as possible, removing the `pattern`s:

![grafik](https://github.com/idaho/hassio-trash-card/assets/11297070/a55b3306-3cb5-4583-80b5-ae8b3a37aa07)

That does not make a difference.

Can you please tell me what I need to do in order to fix this? Thank you in advance :)

**Comment by tchellomello** [comment]
Same here
